name: Create Monday.com Task
on:
  issues:
    types: [labeled]
jobs:
  add-monday-id:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: "Create Monday.com Task"
        if: github.event.label.name == 'monday test'
        uses: actions/github-script@v7
        env:
          MONDAY_KEY: ${{ secrets.MONDAY_KEY }} 
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/createMondayTask.js')
            await action({github, context})
