name: Remove Label from Monday.com Task
on:
  issues:
    types: [unlabeled]
jobs:
  remove-monday-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: "Remove Label from Monday.com Task"
        if: |
          github.event.label.name == 'design' ||
          github.event.label.name == 'a11y' ||
          github.event.label.name == 'figma changes' ||
          github.event.label.name == 'spike'
        uses: actions/github-script@v7
        env:
          MONDAY_KEY: ${{ secrets.MONDAY_KEY }} 
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/removeMondayLabel.js')
            await action({ context })
