name: Update Monday.com Labels
on:
  issues:
    types: [labeled]
jobs:
  add-monday-id:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: "Create Monday.com Task"
        uses: actions/github-script@v7
        env:
          MONDAY_KEY: ${{ secrets.MONDAY_KEY }} 
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/updateMondayLabels.js')
            await action({ context })
