name: Update Monday.com Milestone 
on:
  issues:
    types: [milestoned, demilestoned]
jobs:
  update-monday-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Update Monday.com Milestone"
        uses: actions/github-script@v7
        env:
          MONDAY_KEY: ${{ secrets.MONDAY_KEY }} 
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/updateMondayDate.js')
            await action({github, context})
