name: Add Monday.com ID to Issue Summary
on:
  # issues:
  #   types: [labeled]
jobs:
  add-monday-id:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: "Add Monday.com ID to Issue Summary"
        if: github.event.label.name == 'monday.com sync'
        uses: actions/github-script@v7
        env:
          MONDAY_KEY: ${{ secrets.MONDAY_KEY }} 
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addMondayIDtoBody.js')
            await action({github, context})
